### ISSUE TITLE
Slipfinn arcana e4 can't be disabled, and also still work even if you have 0 point in e4

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1486]

**Comment by redledcat** [comment]
I'm doing something wrong probably but disabling works for me? Fixed in last update maybe, please confirm

**Comment by TheVietboi** [comment]
yeah, it's fixed now. thank you

**Comment by redledcat** [comment]
I didn't fix it, either it was your local problem or someone else fixed it (?)
