### ISSUE TITLE
Seinaru E1 and Bloodstone Boots

### ISSUE THREAD

**Issue by ChalkyBrush** [ChalkyBrush/roshpit-bug-tracker#156]
Having a short cooldown on seinaru E can cause Seinaru to be perma-silenced from E1

"when u making e and use another e before fall but u touch one creep with first e, game thinks that u are on e1 now and get freeze you" - Davi

**Comment by redledcat** [comment]
#20

**Comment by ChalkyBrush** [comment]
pretty sure this is fixed, although TBH I couldn't reproduce it even with -wtf mode on and spamming 

I changed a few things so just request to reopen if its still bugged

**Comment by redledcat** [comment]
@ChalkyBrush 
Not fixed. (Dont know if there is special "request" function)
![20171117151518_1](https://user-images.githubusercontent.com/32621322/32946847-e3e9c5f2-cba1-11e7-84e8-d0dd991b4830.jpg)
Try to reproduce it without -wtf, it took me 1 try to do it and 60k of crystals.
1)Bloodstone+Mordiggus, level up E1 ONLY
2)Prepare a bunch of creeps
3)Lower HP to <30
4)Jump in the mass of creeps
5)Spam E while Seinaru switching targets, even 1 rune of E1 enough to reproduce.
6) Done
Direction of  jump
![20171117151518_1](https://user-images.githubusercontent.com/32621322/32947038-a9b34bdc-cba2-11e7-95ee-c9f52dbcbf16.jpg)

**Comment by redledcat** [comment]
It happens bcs Seinaru has to be in two concurrent E1 states simultaneously? 
Maybe if new queue of E1 will not concure with first, but will add to first, it solves the issue?
(Btw, I just tried it again and bug with first try again. That's surely not hard to reproduce)

**Comment by redledcat** [comment]
I've even downloaded OBS to catch this moment.
https://youtu.be/q4TqFBp0NEs

**Comment by ChalkyBrush** [comment]
100% fixed. I needed the video to see how it worked. I assumed you were using E multiple times before E1 triggers.
