### ISSUE TITLE
Seinaru e1-e4

### ISSUE THREAD

**Issue by Darkness3010** [ChalkyBrush/roshpit-bug-tracker#20]
seinaru e1 sometimes silences u and puts u in a state like the cutscenese after it ends, often this causes death ppl that play seinaru more than me say that it might be an issue while having e4 lvled

**Comment by StillStealSteel** [comment]
Can confirm this. Actually seinaru with mordigus and bloodstone boots has this bug like every few minutes.

**Comment by ChalkyBrush** [comment]
should be fixed

**Comment by redledcat** [comment]
That does not fixed, @ChalkyBrush.
Kit for guaranteed reproduction:
1)Bloodstone,Mordiggus
2)E1 leveled up (nothing else is needed)
3)Enter redfall legend map, gather some __tanky__ mobs around, which wont die in one hit. (Druids, spawner units) (To have E fully gone off cd while supersayaning them)
4)Jump with E1, and spam E during the flight.
5)Congrats, you made it.
![20171030114200_1](https://user-images.githubusercontent.com/32621322/32161701-3dbfa070-bd5f-11e7-9e92-afa3ea2254a4.jpg)

**Comment by redledcat** [comment]
But bug cleance if creep which cause the bug state, dies.
