### ISSUE TITLE
Seinaru - Arcana Q can bug key wisp in Tanari Wind temple into the ground

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#309]
@noctowld:
https://media.discordapp.net/attachments/299728973380976651/406345146813382656/unknown.png?width=451&height=254
https://media.discordapp.net/attachments/299728973380976651/406343184612982785/unknown.png?width=451&height=254
me:
https://youtu.be/7Yx0oikF_vE?t=59

**Comment by redledcat** [comment]
Steps of reproduction:
1. Have head arcana on
2. Have autoattack enabled
3. Press Q the way wisp in on the travelling path of Q spell and Q has long distance
4. Seinaru crits wisp in the air with q1(?) and wisp changes its height below ground

**Comment by ChalkyBrush** [comment]
fixed

**Comment by redledcat** [comment]
@ChalkyBrush not fixed!
Not sure, but it seems boots arcana can bug it too.
Played with friend (which has double arcana build) and he accidently put that wisp into the ground. 2 games in a row.

**Comment by redledcat** [comment]
reopen please

**Comment by redledcat** [comment]
So far I tested that again for 15 minutes, and have not got a problem, but I managed to put him once half way below floor with Q1 samurai crit, which tosses wisp in the air, then returns him lower than his position was.
I think this only can happen when Q1 applies in the air when wisp has negative vertical speed (falling), so q1 applies, then returns wisp on "0" level on ground, then he falling further bcs has vector of speed turned down.

**Comment by redledcat** [comment]
I think I got it right. 
To bug it Seinaru has to target Q in the way so key wisp will be in the middle of Q travel, and enemy will be in the end of it, in spot where Q spell was casted. Autoattack should be enabled, and if Seinaru hits key wisp with Q1 crit, wisp will be pushed up in the air with return below the ground level.
That looks like this.
![default](https://user-images.githubusercontent.com/32621322/42203320-b533cd9c-7e9e-11e8-978c-9e49db050a47.png)

**Comment by Nintai** [comment]
Should be fixed already.
