### ISSUE TITLE
Paladin Penance still bugged.

### ISSUE THREAD

**Issue by FortuneReborn** [ChalkyBrush/roshpit-bug-tracker#67]
Issue 51 is alive and kicking. Up for round 5+?
![570_20171021130114_1](https://user-images.githubusercontent.com/3812172/31851175-79e8314e-b660-11e7-8028-20c41205ecf5.png)
A morphling wavedashed as the Penance Projectile that was targeting at him landed, causing my W to never come off cooldown. (Don't know why it goes on cooldown in the first place)

**Comment by FortuneReborn** [comment]
Theory: You balance Penance by only allowing a certain amount of projectiles to exist of it.
Theory: You do this by upping a counter on creation, and lowering the counter when it ends properly. (By hitting, and failing to roll to bounce again.)
Now, I don't know what you did to fix it, but the current issue is as follows: Penance works fine for a long time. Until X projectiles failed to end properly. Probably because they get disjointed. It then goes on cooldown. Dying lowers the counter by one, however! This means that if you get bugged and die, you will be able to have a single Penance Projectile out at all times (See attached files)
There's plenty of ways to fix this. You could do a check whenever you cast W, though that might be a pain, lag-wise. You could add in a time-limit, if the projectile didn't end 10 seconds after it got launched, lower the counter either way. But that means that every projectile now has to keep track of that.
And I do wonder, if my theory is true, and you do keep a counter, is that necessary? I've never had the slightest amount of lag because of W (I realize that might be because the cast is limited by the system)
Anyway, that's the findings. Here is a pic of what happens when you get bugged and die. The first picture is before shooting, the second has the projectile in mid-air and the third is upon it landing.

**Comment by FortuneReborn** [comment]
![570_20171021130836_1](https://user-images.githubusercontent.com/3812172/31851230-e4f7fa5e-b661-11e7-8eae-9218bc23affa.png)
![570_20171021130842_1](https://user-images.githubusercontent.com/3812172/31851231-e87c828a-b661-11e7-8961-e4d2ff8025cc.png)
![570_20171021130847_1](https://user-images.githubusercontent.com/3812172/31851233-eb599452-b661-11e7-82d0-48d9778f78d2.png)
I hope the order works out.

**Comment by FortuneReborn** [comment]
Dying multiple times does not allow multiple casts. Only ever one.

**Comment by ChalkyBrush** [comment]
should be fixed. just ask to reopen this if its not

**Comment by redledcat** [comment]
New info.
I've seen some reports in steam, I've tried it and it's easy to reproduce.
Issue: some specific mobs and bosses do not cleance penance counter.
I've used max spam build with W mask and got 8 stacks of penance just on Void boss, and game allowed me to fire only 2 lances a time.
![20171022132245_1](https://user-images.githubusercontent.com/32621322/31861001-839b5436-b724-11e7-9f0a-6c20e89fd070.jpg)
Getting 10 or 11 same way participating in several boss kill does the same.

**Comment by FortuneReborn** [comment]
![570_20171022143632_1](https://user-images.githubusercontent.com/3812172/31862054-f887bac4-b737-11e7-9d4d-0d7409f37130.png)
Yup. Plenty of bug still around.

**Comment by FortuneReborn** [comment]
![570_20171022221241_1](https://user-images.githubusercontent.com/3812172/31865866-60d33f84-b776-11e7-88e0-45cb7c3f643b.png)
Confirmed, Faceless is a very good away to make the game unplayable.

**Comment by FortuneReborn** [comment]
(It also persists through death, and chiseling. (The tooltip will disappear, but on equip I go back to "having 9 lances")

**Comment by FortuneReborn** [comment]
![570_20171022232244_1](https://user-images.githubusercontent.com/3812172/31866473-3f429e8c-b780-11e7-8759-0e0631b09c97.png)
![570_20171022232305_1](https://user-images.githubusercontent.com/3812172/31866475-48da2f6e-b780-11e7-8b07-427f90e62485.png)
It is things that become untargetable or immune. I can't kill the boss because of the bug. I got 11 stacks because you can always cast one... or something.

**Comment by FortuneReborn** [comment]
@ChalkyBrush
