### ISSUE TITLE
[Particles] W1 bara ghost omniknights are missing, particles which are using leshrac stun are missing (like demons' in sea fortress)

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#767]

**Comment by redledcat** [comment]
"sea_fortress_barnacle_behemoth"

**Comment by redledcat** [comment]
"sea_fortress_barnacle_colossus"	
and valdun jump

**Comment by redledcat** [comment]
however, tanari_ancient and elemental warlord E have proper split earth parcticle

**Comment by redledcat** [comment]
and autumn cragnataur - wild leap ability (Missing)

**Comment by redledcat** [comment]
crimson eliminator (leshrac) - split earth

**Comment by redledcat** [comment]
crymsyth corruptor "exploding" effect when he splits on copies, missing particle too

**Comment by redledcat** [comment]
crymsith demon knight - crushing leap

**Comment by ChalkyBrush** [comment]
fixed

**Comment by redledcat** [comment]
not fixed, W1 still uses _a_b names.
You really should parse files for these old names better, or I can just do it manually.
Actually found some for hydroxis and veno modifier icons, but not sure how to be with particles
